# .github/workflows/release.yml
# Builds .NET binaries for multiple platforms
name: release
on:
  release:
    types: [published]
  push:
    tags:
      - 'v*'
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        runtime: [win-x64, linux-x64, osx-x64]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      
      - name: Build Release
        run: |
          dotnet publish src/PgsToSrt \
            --configuration Release \
            --runtime ${{ matrix.runtime }} \
            --self-contained true \
            --output ./release-${{ matrix.runtime }} \
            -p:PublishSingleFile=false \
            -p:PublishReadyToRun=false
      
      - name: Create Release Archive
        run: |
          cd release-${{ matrix.runtime }}
          if [[ "${{ matrix.runtime }}" == win-* ]]; then
            zip -r ../PgsToSrt-${{ github.ref_name }}-${{ matrix.runtime }}.zip .
          else
            tar -czf ../PgsToSrt-${{ github.ref_name }}-${{ matrix.runtime }}.tar.gz .
          fi
      
      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          files: PgsToSrt-${{ github.ref_name }}-${{ matrix.runtime }}.*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
