# .github/workflows/release.yml
# Builds .NET binaries when you create version tags
name: release
on:
  push:
    tags:
      - 'v*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      
      - name: Build Release
        run: |
          dotnet publish src/PgsToSrt \
            --configuration Release \
            --runtime linux-x64 \
            --self-contained false \
            --output ./release
      
      - name: Create Release Archive
        run: |
          cd release
          zip -r ../PgsToSrt-${{ github.ref_name }}.zip .
      
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: PgsToSrt-${{ github.ref_name }}.zip
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
